  (defun color-theme-pastelmac ()
    "Color theme by Brian Mastenbrook, created 2006-10-29."
    (interactive)
    (color-theme-install
     '(color-theme-pastelmac
       ((background-color . "#EAF0F0")
        (background-mode . light)
        (border-color . "black")
        (cursor-color . "SlateGray4")
        (foreground-color . "black")
        (mouse-color . "black"))
       (default ((t (:stipple nil :background "#EAF0F0" :foreground "black"))))
       (comint-highlight-prompt ((t (:foreground "purple4"))))
       (erc-action-face ((t nil)))
       (erc-current-nick-face ((t (:inherit erc-nick-msg-face :weight bold))))
       (erc-direct-msg-face ((t (:inherit font-lock-comment-face
:weight bold))))
       (erc-error-face ((t (:inherit font-lock-warning-face))))
       (erc-input-face ((t (:inherit font-lock-builtin-face))))
       (erc-nick-default-face ((t (:inherit
font-lock-function-name-face :weight bold))))
       (erc-nick-msg-face ((t (:inherit font-lock-comment-face :weight bold))))
       (erc-notice-face ((t (:inherit font-lock-string-face :weight bold))))
       (erc-timestamp-face ((t (:inherit font-lock-variable-name-face))))
       (font-lock-builtin-face ((((class color) (background light))
(:foreground "Maroon"))))
       (font-lock-comment-face ((((class color) (background light))
(:foreground "Cyan4"))))
       (font-lock-constant-face ((((class color) (background light))
(:foreground "DarkRed"))))
       (font-lock-function-name-face ((((class color) (background
light)) (:foreground "DarkBlue"))))
       (font-lock-keyword-face ((((class color) (background light))
(:foreground "Purple4"))))
       (font-lock-string-face ((((class color) (background light))
(:foreground "Gray30"))))
       (font-lock-type-face ((((class color) (background light))
(:foreground "Aquamarine4"))))
       (font-lock-variable-name-face ((((class color) (background
light)) (:foreground "tomato"))))
       (font-lock-warning-face ((((class color) (background light))
(:foreground "DarkRed" :weight bold))))
       (gnus-cite-face-1 ((((class color) (background light))
(:foreground "firebrick3"))))
       (gnus-cite-face-2 ((((class color) (background light))
(:foreground "aquamarine4"))))
       (gnus-cite-face-3 ((((class color) (background light))
(:foreground "indianred4"))))
       (gnus-cite-face-4 ((((class color) (background light))
(:foreground "steelblue4"))))
       (gnus-cite-face-5 ((((class color) (background light))
(:foreground "DeepPink4"))))
       (gnus-cite-face-6 ((((class color) (background light))
(:foreground "SeaGreen4"))))
       (gnus-header-from-face ((((class color) (background light))
(:foreground "DarkSlateGray"))))
       (gnus-header-newsgroups-face ((((class color) (background
light)) (:foreground "Purple4" :slant italic))))
       (gnus-header-subject-face ((((class color) (background light))
(:foreground "DarkSlateGrey"))))
       (gnus-splash-face ((((class color) (background light)) nil)))
       (gnus-summary-normal-read-face ((((class color) (background
light)) (:foreground "aquamarine4"))))
       (highlight ((((class color) (background light)) (:background
"lightsteelblue2"))))
       (minibuffer-prompt ((t (:foreground "steelblue4"))))
       (mode-line ((((type x w32 mac) (class color)) (:background
"grey90" :foreground "grey0" :box (:line-width -1 :color "grey70")))))
       (mode-line-inactive ((t (:inherit mode-line :foreground "grey50"))))
       (sldb-condition-face ((t (:inherit font-lock-type-face))))
       (sldb-frame-line-face ((t (:inherit font-lock-builtin-face))))
       (sldb-restart-face ((t (:inherit font-lock-doc-face))))
       (sldb-restart-number-face ((t (:inherit font-lock-constant-face))))
       (sldb-restart-type-face ((t (:inherit font-lock-type-face))))
       (sldb-topline-face ((t (:inherit font-lock-warning-face))))
       (slime-repl-input-face ((t (:foreground "maroon"))))
       (slime-repl-output-face ((t (:inherit font-lock-comment-face))))
       (w3m-anchor-face ((((class color) (background light))
(:foreground "SteelBlue4"))))
       (w3m-arrived-anchor-face ((((class color) (background light))
(:foreground "Purple4"))))
       (w3m-header-line-location-content-face ((((class color)
(background light)) (:background "Gray90" :foreground "Cyan4"))))
       (w3m-header-line-location-title-face ((((class color)
(background light)) (:background "Gray90" :foreground "Maroon")))))))

  (add-to-list 'color-themes '(color-theme-pastelmac "Pastel Mac"
"Brian Mastenbrook <brian@mastenbrook.net>"))
  ;(color-theme-initialize)
;  )

;(color-theme-pastelmac)
(provide 'color-theme-pastelmac)
