theme = "solarized_light"

[editor]
auto-format = true
bufferline = "always"
cursorline = true
true-color = true
auto-pairs = false
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"C-]" = "goto_definition"
F6 = ":theme solarized_light"
F5 = ":theme meliora"
q = ":bc"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_end", "yank", "delete_selection"]
g = { q = ":reflow", o = ":noop %sh{gh browse %{buffer_name}:%{cursor_line} -c=%sh{git rev-parse HEAD}}" }
"]" = { b = "goto_next_buffer" }
"[" = { b = "goto_previous_buffer" }
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"

[keys.insert]
"C-[" = "normal_mode"
