theme = "solarized_light"

[editor]
line-number = "relative"
mouse = false
auto-format = true
auto-pairs = false
bufferline = "never"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"C-]" = "goto_definition"

[keys.insert]
"C-[" = "normal_mode"
