theme = "amberwood"

[editor]
auto-format = true
bufferline = "always"
cursorline = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"C-]" = "goto_definition"
F5 = ":theme solarized_light"
F6 = ":theme amberwood"
q = ":bc"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
g = { q = ":reflow" }
"]" = { b = "goto_next_buffer" }
"[" = { b = "goto_previous_buffer" }

[keys.insert]
"C-[" = "normal_mode"
