[[language]]
name = "go"
formatter = { command = "goimports" }
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "haskell"
auto-format = true
formatter = { command = "stylish-haskell", args = [] }

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "hclfmt", args = [] }
